version: '3.8'

services:
  django:
    image: 266735827053.dkr.ecr.us-west-1.amazonaws.com/engagex-streaming:latest
    command: /bin/sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 EngageX_Streaming.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - tmp-data:/tmp
    env_file:
      - .env

  celery:
    image: 266735827053.dkr.ecr.us-west-1.amazonaws.com/engagex-streaming:latest
    command: celery -A EngageX_Streaming worker --loglevel=info --pool=threads
    volumes:
      - tmp-data:/tmp
    env_file:
      - .env

  celery-flower:
    image: 266735827053.dkr.ecr.us-west-1.amazonaws.com/engagex-streaming:latest
    command: celery -A EngageX_Streaming flower --loglevel=info
    ports:
      - "5555:5555"
    env_file:
      - .env
  
  volumes:
    tmp-data: