version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

      # PostgreSQL
      - POSTGRESQL_DATABASE_NAME=${POSTGRESQL_DATABASE_NAME}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_SERVER_NAME=${POSTGRESQL_SERVER_NAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - PORT=5432

      # OpenAI and Deepgram API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}

      # AWS SES Config
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=true
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}

      # AWS S3 Config
      - USE_S3=true
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      # Intuit Config
      - INTUIT_VERIFIER_TOKEN=${INTUIT_VERIFIER_TOKEN}
      - INTUIT_CLIENT_ID=${INTUIT_CLIENT_ID}
      - INTUIT_CLIENT_SECRET=${INTUIT_CLIENT_SECRET}
      - NEW_INTUIT_REDIRECT_URI=${NEW_INTUIT_REDIRECT_URI}
      - INTUIT_ENVIRONMENT=${INTUIT_ENVIRONMENT}

      # Stripe Config
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

      # Redis URL
      - REDIS_URL=${REDIS_URL}

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A EngageX_Streaming worker --loglevel=info --pool=threads
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

      # Shared environment variables
      - POSTGRESQL_DATABASE_NAME=${POSTGRESQL_DATABASE_NAME}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_SERVER_NAME=${POSTGRESQL_SERVER_NAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - PORT=5432

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=true
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}

      - USE_S3=true
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      - INTUIT_VERIFIER_TOKEN=${INTUIT_VERIFIER_TOKEN}
      - INTUIT_CLIENT_ID=${INTUIT_CLIENT_ID}
      - INTUIT_CLIENT_SECRET=${INTUIT_CLIENT_SECRET}
      - NEW_INTUIT_REDIRECT_URI=${NEW_INTUIT_REDIRECT_URI}
      - INTUIT_ENVIRONMENT=${INTUIT_ENVIRONMENT}

      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

      - REDIS_URL=${REDIS_URL}

  celery-flower:
    build: .
    command: celery -A EngageX_Streaming flower --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

      # Same shared variables
      - POSTGRESQL_DATABASE_NAME=${POSTGRESQL_DATABASE_NAME}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_SERVER_NAME=${POSTGRESQL_SERVER_NAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - PORT=5432

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=true
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}

      - USE_S3=true
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      - INTUIT_VERIFIER_TOKEN=${INTUIT_VERIFIER_TOKEN}
      - INTUIT_CLIENT_ID=${INTUIT_CLIENT_ID}
      - INTUIT_CLIENT_SECRET=${INTUIT_CLIENT_SECRET}
      - NEW_INTUIT_REDIRECT_URI=${NEW_INTUIT_REDIRECT_URI}
      - INTUIT_ENVIRONMENT=${INTUIT_ENVIRONMENT}

      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

      - REDIS_URL=${REDIS_URL}